language: cpp

matrix:
  include:
    - os: linux
      #addons:
      #  apt:
      #    sources: 
      #      - ubuntu-toolchain-r-test
      #    packages:
      #      - g++-7
      env: COMPILER_ENV="CC=gcc-7 && CXX=g++-7"

before_install:
  # Set the ${CC} ${CXX} variables properly.
  - eval ${COMPILER_ENV}

  # Add CI scripts to PATH.
  - export PATH="${TRAVIS_BUILD_DIR}/tools:${PATH}"

  # Create path for dependencies.
  - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
  - mkdir -p ${DEPS_DIR}
  - cd ${DEPS_DIR}

install:
  - ci_install-cmake.sh 3.10.2 ${TRAVIS_OS_NAME}

#  - ci_install-clang.sh 5.0.1 ${TRAVIS_OS_NAME}

before_script:
  - cd ${TRAVIS_BUILD_DIR}
#  - which ${CC}
#  - which ${CXX}
  - which cmake
 # - which clang-format

 # - ${CXX} --version
  - cmake --version
 # - clang-format --version
 #cd ${TRAVIS_BUILD_DIR}

script:
  - mkdir -p build
  - cd build
#  - cmake ..
#  - make
#  - cd -

#after_script:
  # Check code format using clang-format.
#  - ci_format.sh
