language: cpp
sudo: required
group: travis_latest

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - g++-7
          sources: 
            - ubuntu-toolchain-r-test
      env: GCC=7 CMAKE=3.10.2

before_install:
  # Add CI scripts to PATH.
  - export PATH=${TRAVIS_BUILD_DIR}/tools:${PATH}

  # Create path for dependencies.
  - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
  - mkdir -p ${DEPS_DIR}
  - cd ${DEPS_DIR}

install:
  # cmake
  - ci_install-cmake.sh ${CMAKE} ${TRAVIS_OS_NAME}
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}

before_script:
  # Set compilers.
  #- eval ${COMPILER_ENV}
  - export CC=gcc-${GCC}
  - export CXX=g++-${GCC}

  # Check versions of used tools.
  - ${CXX} --version
  - cmake --version
  - clang-format --version

  - cd ${TRAVIS_BUILD_DIR}

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - cd ${TRAVIS_BUILD_DIR}

after_script:
  # Check code format using clang-format.
  - ci_format.sh .
