language: cpp

matrix:
  include:
    - os: linux
      #addons:
      #  apt:
      #    sources: 
      #      - ubuntu-toolchain-r-test
      #    packages:
      #      - g++-7
      env: COMPILER_ENV="CC=gcc-7 && CXX=g++-7"

before_install:
  # Set the ${CC} ${CXX} variables properly.
  - eval ${COMPILER_ENV}

install:
#  - CMAKE_URL="https://cmake.org/files/v3.10/cmake-3.10.2-Linux-x86_64.tar.gz"
#  - mkdir -p cmake
#  - wget --no-check-certificate --quiet "${CMAKE_URL}" 
#  - tar --strip-components=1 -xf cmake-3.10.2-Linux-x86_64.tar.gz -C cmake
#  - tar -xf cmake-3.10.2-Linux-x86_64.tar.gz -C cmake
  - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
  - mkdir -p ${DEPS_DIR}
  - cd ${DEPS_DIR}
  - tools/ci_install-cmake.sh 3.10.2 ${TRAVIS_OS_NAME}
  - export PATH="${DEPS_DIR}/cmake/bin:${PATH}"

#  - tools/ci_install-clang.sh 5.0.1 ${TRAVIS_OS_NAME}
  - echo ${PATH}

before_script:
  - cd ${TRAVIS_BUILD_DIR}
#  - which ${CC}
#  - which ${CXX}
  - which cmake
 # - which clang-format

 # - ${CXX} --version
  - cmake --version
 # - clang-format --version
 #cd ${TRAVIS_BUILD_DIR}

script:
  - mkdir -p build
  - cd build
#  - cmake ..
#  - make
#  - cd -

#after_script:
  # Check code format using clang-format.
#  - tools/ci_format.sh
