language: cpp
sudo: required
group: travis_latest

matrix:
  include:
    - os: linux
      env: COMPILER=gcc COMPILER_VER=7 CMAKE_VER=3.10.2
    - os: linux
      env: COMPILER=clang COMPILER_VER=6.0 CMAKE_VER=3.10.2
    - os: osx
      osx_image: xcode9.2
      env: COMPILER=gcc COMPILER_VER=7 CMAKE_VER=3.10.2
    - os: osx
      osx_image: xcode9.2
      env: COMPILER=clang COMPILER_VER=6.0 CMAKE_VER=3.10.2

before_install:
  # Add CI scripts to PATH.
  - export PATH=${TRAVIS_BUILD_DIR}/tools/ci:${PATH}

  # Create path for dependencies.
  - mkdir -p deps
  - cd deps

install:
  - install-${COMPILER}.sh ${COMPILER_VER} ${TRAVIS_OS_NAME}
  - install-cmake.sh ${CMAKE_VER} ${TRAVIS_OS_NAME}
  - install-clang.sh 6.0 ${TRAVIS_OS_NAME} false

before_script:
  - export-paths.sh
  - source ${HOME}/.bash_profile

  # Check versions of used tools.
  - cmake --version
  - clang-format --version

  - cd ${TRAVIS_BUILD_DIR}

script:
  # Build.
  - mkdir -p build
  - cd build
  - cmake -DWITH_TESTS=ON ..
  - make

  # Run tests.
  - ctest -R UnitTests
  - cd -

after_script:
  # Check code format using clang-format.
  - check-format.sh .
